version: '3'

networks:
  default:
    external:
        name: localdev

volumes:
  vod:
  web:
  db:

services:
  web:
    build: ./backend
    restart: unless-stopped
    environment:
      - DATABASE_NAME=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_USER=postgres
      - DATABASE_HOST=db
      - PORT=8080
    volumes:
      - web:/app
      # - vod:/vod
    ports:
      - 8080:8080
    networks:
      - default
    depends_on:
      - db
      # - nginx-rtmp

  db:
    image: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_DB=postgres
      - POSRGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    networks:
      - default

  # nginx-rtmp:
  #   image: alfg/nginx-rtmp
  #   restart: unless-stopped
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx-rtmp.conf.template
  #   ports:
  #     - 1935:1935
  #     - 8081:80
  #   networks:
  #     - default

  nginx-vod:
    image: nytimes/nginx-vod-module
    restart: unless-stopped
    volumes:
      - ./frontend/out:/opt/static/frontend
      - ./vod:/opt/static/videos
      - ./nginx-vod.conf:/usr/local/nginx/conf/nginx.conf
    ports:
      - 80:80
    depends_on: 
      - web
