version: '3'

# volumes:
#   videos:

services:
  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - DATABASE_NAME=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_USER=postgres
      - DATABASE_HOST=db
      - PORT=8080
    ports:
      - 8080:8080
    networks:
      - default
    depends_on:
      - db

  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - NODE_ENV=development
      - GATSBY_WEBPACK_PUBLICPATH=/
    ports:
      - 8000:8000
      - 9929:9929
      - 9230:9230
    networks:
      - default

  db:
    image: postgres:alpine
    restart: unless-stopped
    environment:
      - POSTGRES_DB=postgres
      - POSRGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    networks:
      - default

  nginx:
    build:
      context: nginx
      dockerfile: Dockerfile 
    restart: unless-stopped
    volumes:
      - ./videos:/www/static/videos
    ports:
      - 1935:1935
      - 8090:80
    networks:
      - default