# Configuration file

# Time in minutes when jwt token expires
JWTExp = 10000
# Secret used to create jwt token
JWTSecret = "secret"

# Source file directory
SD = "/uploaded/"
# Temporary (a.k.a file in trancoding proccess) directory
TD = "/transcoding/"
# Destination file directory
DD = "/videos/"
# Thumbnail directory
TND = "/videos/thumbnails/"
# Absolute path to go directory
APTGD = ""

# If true debug transcoder by transcoding only interval between DebugStart-DebugEnd
Debug = true
DebugStart = "00:00:00"
DebugEnd = "00:00:30"

# Video bit rate 
VBW = 2500

# Log file path and name
LogP = "info.log"

# Available file formats to be uploaded
FileTypes = [".mkv", ".mp4", ".avi", ".mov", ".mpg", ".wmv", ".webm"]